export const SQUAD_SWARM_ESCROW_ABI = [
  {
    type: "function",
    name: "createContract",
    inputs: [
      { name: "contractId", type: "bytes32", internalType: "bytes32" },
      { name: "squad", type: "address", internalType: "address" },
      { name: "paymentSplitter", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "totalAmount", type: "uint256", internalType: "uint256" },
      { name: "upfrontBps", type: "uint256", internalType: "uint256" },
      { name: "defaultClientBps", type: "uint256", internalType: "uint256" },
      { name: "defaultSquadBps", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [{ name: "contractId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "releaseMilestone",
    inputs: [
      { name: "contractId", type: "bytes32", internalType: "bytes32" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "complete",
    inputs: [{ name: "contractId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "raiseDispute",
    inputs: [{ name: "contractId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveDispute",
    inputs: [
      { name: "contractId", type: "bytes32", internalType: "bytes32" },
      { name: "clientBps", type: "uint256", internalType: "uint256" },
      { name: "squadBps", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "autoSplit",
    inputs: [{ name: "contractId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getContract",
    inputs: [{ name: "contractId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SquadSwarmEscrow.Contract",
        components: [
          { name: "client", type: "address", internalType: "address" },
          { name: "squad", type: "address", internalType: "address" },
          { name: "paymentSplitter", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "contract IERC20" },
          { name: "totalAmount", type: "uint256", internalType: "uint256" },
          { name: "upfrontBps", type: "uint256", internalType: "uint256" },
          { name: "depositedAmount", type: "uint256", internalType: "uint256" },
          { name: "releasedAmount", type: "uint256", internalType: "uint256" },
          { name: "status", type: "uint8", internalType: "enum SquadSwarmEscrow.Status" },
          { name: "disputeDeadline", type: "uint256", internalType: "uint256" },
          { name: "defaultClientBps", type: "uint256", internalType: "uint256" },
          { name: "defaultSquadBps", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "contracts",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "client", type: "address", internalType: "address" },
      { name: "squad", type: "address", internalType: "address" },
      { name: "paymentSplitter", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "contract IERC20" },
      { name: "totalAmount", type: "uint256", internalType: "uint256" },
      { name: "upfrontBps", type: "uint256", internalType: "uint256" },
      { name: "depositedAmount", type: "uint256", internalType: "uint256" },
      { name: "releasedAmount", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "enum SquadSwarmEscrow.Status" },
      { name: "disputeDeadline", type: "uint256", internalType: "uint256" },
      { name: "defaultClientBps", type: "uint256", internalType: "uint256" },
      { name: "defaultSquadBps", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "ContractCreated",
    inputs: [
      { name: "contractId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "client", type: "address", indexed: false, internalType: "address" },
      { name: "squad", type: "address", indexed: false, internalType: "address" },
      { name: "totalAmount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { name: "contractId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Released",
    inputs: [
      { name: "contractId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "to", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DisputeRaised",
    inputs: [
      { name: "contractId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "deadline", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DisputeResolved",
    inputs: [
      { name: "contractId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "clientAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "squadAmount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Completed",
    inputs: [
      { name: "contractId", type: "bytes32", indexed: true, internalType: "bytes32" },
    ],
    anonymous: false,
  },
] as const;
